### ISSUE TITLE
Network Firewall Rule Group: Traffic to Inspect

### ISSUE THREAD

**Issue by IpsumAudite** [aws-samples/aws-networkfirewall-cfn-templates#8]
I have been trying to find examples of the "Traffic to Inspect" being set in CloudFormation for type `AWS::NetworkFirewall::RuleGroup` but I cannot find any examples or anywhere in the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-networkfirewall-rulegroup-rulessourcelist.html) where it is listed. See screenshot for how it is set in the console. 

<img width="1102" alt="Screenshot 2024-04-23 at 3 55 25 PM" src="https://github.com/aws-samples/aws-networkfirewall-cfn-templates/assets/17183076/1109cd50-51b1-45b8-b85c-5a7e2fc09e9b">

Is HTTPS set implicitly in some other configuration? Is the code you have here setting both HTTP and HTTPS? 

Thank you!

**Comment by lawtonpittenger** [comment]
Hello,
This is only applicable for the domain list rule groups, see example below:

```
  DomainAllowStatefulRuleGroup:
    Type: 'AWS::NetworkFirewall::RuleGroup'
    Properties:
      RuleGroupName: !Sub "domain-allow-${AWS::StackName}"
      Type: STATEFUL
      Capacity: 100
      RuleGroup:
        RuleVariables:
          IPSets:
            HOME_NET:
              Definition:
                - "10.0.0.0/8"
        RulesSource:
          RulesSourceList:
            TargetTypes:
              - HTTP_HOST
              - TLS_SNI
            Targets: 
              - ".amazon.com"
            GeneratedRulesType: "ALLOWLIST"
      Tags:
        - Key: Name
          Value: !Sub "domain-allow-${AWS::StackName}" 
```
